# Generated by Django 5.1 on 2024-09-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_otprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
